### ISSUE TITLE
license policy for the talks

### ISSUE THREAD

**Issue by nuest** [datascience-meetup-muenster/talks#1]
It would be great if there would be a global definition, or a per-talk statement, for a license of the information in this repo. For example CC-BY International?

**Comment by t-pfaff** [comment]
@nuest If it's on a per-talk basis, would you add a link to the license below the talk in readme.md?

**Comment by nuest** [comment]
It should be part of the talk then, e.g. on the first/last slide, or even with a small icon on every slide... people might link directly to the talks. Then I'd just add a note to the readme that license information is within the talks, and contents of this repository might be provided under different open or non-open licenses.

**Comment by nuest** [comment]
But you're right, if the talk does not contain it, it would be good to at least put a note in the readme next to the talk title.

**Comment by t-pfaff** [comment]
I guess it's too much effort to ask every speaker to include icons on every slide. I'd rather do it on a per-talk basis and just add the link.
Just did it for my talk: [readme.md](https://github.com/datascience-meetup-muenster/talks/blob/master/meetup-01/readme.md)
How's that, dude with the disc?

**Comment by nuest** [comment]
LGTM
